/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markov;

import java.util.Arrays;
import java.util.HashMap;

/**
 *
 * @author rick
 */
public class charmarkov {

    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
     */

    /**
     * @param args the command line arguments
     *//*
    public static void main(String[] args) {

        String s = "TYLER COWEN: Today I am with Margalit Fox at Chelsea Market. One of my readers wrote to me about Margalit, “She is by far the best writer amongst all those employed by the New York Times.” She is arguably the most humorous writer, has the best sense of irony, and the most inventive writer.\n"
                + "She is, in fact, one of the main writers of obituaries for the New York Times. She also has written two very well-reviewed books, has a third book coming out about historical true crime in Edwardian England, and I’m here to talk with Margalit Fox. Welcome.\n"
                + "MARGALIT FOX: Thank you very much, Tyler.\n"
                + "COWEN: The fact that you write obituaries makes you especially interesting. And my first question has to do with human lives. How well do you feel family and friends actually know a person? You get to know them fairly well when you write their obit. How well do others know them, those closest to them?\n"
                + "FOX: Of course, those closest to them are the ones by definition who know them best. And so, for various reasons, including just one of basic reporting smarts, we are obliged to spend time on the phone with families and close friends where there are such people to be had.\n"
                + "COWEN: But how often is the family or the close friends surprised by what’s in the obituary? Divorces they didn’t know about; children they didn’t know about; they may have been an alcoholic when they were in their 20s; something they did in their career.\n"
                + "FOX: Remember that we the reporter are starting almost always from an agnostic state. Of course, there are essentially two categories of obituaries that the Times does.\n"
                + "One are the marquee names, the presidents, the kings, the queens, the captains of industry, old-time Hollywood film stars, and so on — people who are in the history books, people whom everyone has heard of. Their lives are well documented, and so there are rarely any surprises, either for the family or for the reporter working on the story.\n"
                + "On the other hand, there is this whole other category of people whom I call history’s backstage players, these unsung men and women who are not household names but who, because they invented something, had an idea, wrote something, you know, way back perhaps in the 1940s — they put a wrinkle in the social fabric and changed the world.\n"
                + "I’ve done, for instance, the inventor of the Frisbee, the inventor of Etch A Sketch, the inventor of the plastic lawn flamingo, of Stove Top Stuffing. Now, about those people, although clearly they did something that changed the culture — was transformative in some way — we reporters are almost always going in cold. We’ve very often never heard the name, much less anything about what this person did.\n"
                + "And so, for that, of course, we’re obliged to rely to an extent, with appropriate double-checking and backstopping, on family knowledge because their knowledge is better and of far, far longer duration than ours.\n"
                + "Margalit Fox reads her obituary for John Fairfax\n"
                + "COWEN: What’s the most surprising thing you’ve learned about an ordinary life writing one of these obituaries? Not a famous person but — .\n"
                + "FOX: Well, here’s one. I brought one with me. There was a very good photographer who worked for the Village Voice for many years, a man named Fred McDarrah. He died in 2007. Now, his work as a photographer for the Voice alone would have been more than enough to get him a news obit in our pages, which it did.\n"
                + "He took, for instance, a very famous photo of Bob Dylan, a young Bob Dylan all in black, in Sheridan Square Park in New York, facing the camera and saluting. That photo has been everywhere. That was taken by our guy, Fred McDarrah. And because of when he worked in the fifties and sixties, he was famous for documenting photographically the beat generation.\n"
                + "To my surprise and delight, when I started pulling old clippings and researching the obit, we found that not only did he document the beat generation, but he enterprisingly started a business called Rent-a-Beatnik for these society matrons who wanted to be au courant, wanted to have a beatnik play the bongos or read poetry at their fancy parties in Scarsdale, but didn’t quite know how to go about it.\n"
                + "COWEN: With rental markets and everything, I would say.\n"
                + "FOX: Exactly. So the lede of our obit — we say, “Fred W. McDarrah, a self-described square who was a longtime photographer for the Village Voice documented the unwashed exploits of the Beat generation, and as an enterprising freelance talent agent rented out members of that generation (washed or unwashed) to wide-eyed suburban society gatherings, died,” etc., etc. So that was great fun.\n"
                + "On the structure of obits\n"
                + "COWEN: One thing I find interesting when I read obituaries is how much subtle humor is in them and how much of an attempt is made to make the first sentence be especially interesting. And often the last sentence contains a kind of nugget or surprise or twist on the story. Now, the other parts of the newspaper typically aren’t like this, be it the New York Times or elsewhere.\n"
                + "So why do obituaries have this special status where there’s room in them for this kind of humor and invention? Or alternatively, why don’t more parts of the newspaper actually copy this if it works, which I think it typically does?\n"
                + "FOX: As to what more parts of the newspaper do or don’t do, I can’t speak, but of course, as you know, there are very ironclad conventions for the structure of news articles. Historically, obits were no exception to that. These conventions actually have been in place during the Civil War. And it’s worth digressing about them quickly because they’re quite fascinating.\n"
                + "Anyone who’s ever taken Journalism 101 has heard about the inverted pyramid, which is this upside-down triangle that’s supposed to be the model for the lede paragraph of any news story and in fact for the structure of the news story as it flows along: broad-based information first and then finer- and finer- and finer-grained detail, down to stuff at the end that you could possibly dispense with if you’re short on space.\n"
                + "And that model is an information-processing model. It has endured for over a hundred years because it’s cognitively perfect. It came about during Civil War battle coverage, when they had the medium of telegraphy for the first time available to reporters.\n"
                + "Like much new technology, it was bulky. Lines went down. And reporters learned in a do-or-die sort of way, “Get the broadest information through first, so if the lines go down, at least your readers back in Boston or Baltimore will have something. Your editor will have something to put in the paper.” That model has endured because it’s how we process information. It’s cognitively perfect.\n"
                + "Obits, too, were beholden to that model, plus weighed down further by all of this boilerplate that has to be there — so-and-so died, when, where, of what illness, at what age. And that is why historically obits were considered one of the most boring sections of any daily paper.\n"
                + "Happily, in the last 20 or 30 years, particularly we at the Times have realized that underlying all of that potentially very leaden boilerplate is a pure narrative arc. Because what does an obit do? It’s charged with taking subjects from the cradle — John Doe was born on January 1st, 1900 — to the grave — John Doe died yesterday. That gives you a built-in narrative arc.\n"
                + "And indeed, obits turn out to be the most purely narrative genre in any daily paper. The reason we have these great ledes and we hope great kickers, as we call them, at the end is that we are exploiting very happily this inherent narrative potential that is a news obit.\n"
                + "    And indeed, obits turn out to be the most purely narrative genre in any daily paper. The reason we have these great ledes and we hope great kickers…at the end is that we are exploiting very happily this inherent narrative potential that is a news obit.\n"
                + "COWEN: But in terms of the structure of the newspaper, certain rules and procedures have not been imposed on obituaries that are imposed on other news stories. What do you think it is about the nature of obituaries or maybe their role in the newsroom that has allowed that freedom to evolve?\n"
                + "Because people who report on crimes — you could imagine I’m talking to one of them, and they would say, “This is the perfect narrative arc. We developed all these freedoms” — but typically not. There’s a pretty rigid structure to a crime story.\n"
                + "FOX: See, I don’t know that I agree with your initial premise because there is also a pretty rigid structure to an obit. It’s there. To put it in Chomskyan terms, in old-time Chomskyan terms, it’s the deep structure. It’s there undergirding everything. Otherwise the story wouldn’t cohere. It would fall apart.\n"
                + "COWEN: There’s a birth and a death. Right.\n"
                + "FOX: But all of the stuff is there. The trick is — if you want to make it good art but also have complete fealty to the tenets of journalism, which we must adhere to, the trick is to disguise all of that infrastructure, all of those girders, and to make it — where thematically appropriate — to make it kind of light and frothy and dancing and a really good read.\n"
                + "COWEN: Now, if I look at a lot of British obituaries, it seems to me they often have a different structure. You can tell me in a moment what you think that difference is. But often I see the death buried in the middle of the British obituary.\n"
                + "There’s maybe a greater tendency to poke fun at the person who has passed away. Often the obituary won’t be printed — say, several weeks later, which is not, say, how the New York Times typically operates.\n"
                + "Now, what do you think are the differences between British and American obituaries, and how have they evolved? What accounts for that?\n"
                + "FOX: That’s a huge question, and because I’m not a historian of journalism, I can’t account for how it’s evolved. That’s beyond my ken. British obituaries and British journalism generally — it’s that Fleet Street model — are more catty than news stories in almost any section of an American paper.\n"
                + "Again, we have to have complete fealty to the truth. We have to have complete impartiality. We have to be disinterested in the pure sense of the term where we are detached observers. And an obit is no different. But at the same time, because we have wonderful marquee-name writers in our section — Biff Grimes, Bruce Weber, Sam Roberts — .\n"
                + "COWEN: Margalit Fox.\n"
                + "FOX: Thank you. We are able to put a really interesting gloss — gloss in perhaps both senses of the term — on top of this basic structure that has to be there.\n"
                + "On being the gatekeeper for a highly exclusive club\n"
                + "COWEN: Edward Lowe — he’s the man who invented Kitty Litter. I believe you’ve heard of him. Do you feel he should be more or less famous? In American society as a whole, do you feel the fame incentives for people like Edward Lowe are too strong or too weak?\n"
                + "FOX: Edward Lowe in 1947, as memorialized in the famous obituary by our late great obit writer Robert McG. Thomas, was the man who, because he had an idea one day, invented the product that became known as Kitty Litter. And it did indeed cause social change because it made cats much easier to keep indoors than formerly. For the first time, a few decades later, cats actually passed dogs as the most popular American pet.\n"
                + "So, again, here’s somebody who did something spontaneously because he was inspired and who put a wrinkle in the social fabric. He changed the culture. Now, he wasn’t doing it to get famous.\n"
                + "I don’t — you know, Andy Warhol hadn’t yet said, “In the world of the future, everyone will be famous for 15 minutes.” I think very few people about whom we write do things for fame. The fame comes post hoc, applied by people like us in the news media. I don’t think there’s any incentivization of fame for the vast majority of people about whom we write. In fact, it never even occurred to me.\n"
                + "COWEN: You’re one of the gatekeepers of one of the world’s most exclusive clubs. Numbers I’ve seen — every year about two-and-a-half million Americans pass away. And in that same year, the New York Times might run about, what, a thousand obituaries?\n"
                + "FOX: Right, for space reasons.\n"
                + "COWEN: I realize some of this process may be confidential, but apart from the obvious candidates — former presidents and the like — how is it determined who gets covered, who gets entrance into this highly exclusive club? What are the standards, and what kinds of discussions do you have?\n"
                + "What are some features about a person that maybe wouldn’t be so intuitive to our listeners that actually are quite dispositive for determining whether you let them through the gates?\n"
                + "FOX: There is no one cookie-cutter model for who gets in and who gets out. How could there be? Lives are so different. Indeed, apart from the people who are the shoo-ins — the presidents, the kings and queens — there is this whole other 90 percent of the iceberg that’s hidden but which we may want to expose in our pages. These are these fascinating backstage players, the inventors of Kitty Litter and the lawn flamingo, etc.\n"
                + "What we look for generally — and the question that’s asked by our three section editors, who agonize every day over the volume of submissions we get from families, from funeral homes, stories we read in out-of-town papers, foreign papers, the wire services, things come flooding in, and these decisions have to be made every day. Indeed, it’s like a meeting of the admission committee of the most selective university in the world.\n"
                + "COWEN: And it’s, what, three of you, five of you?\n"
                + "FOX: There are our section head, Bill McDonald, and his two deputies, Jack Kadden and Peter Keepnews. The editors are charged first and last with the responsibility of deciding who gets in every day and roughly the length, to whom it’s assigned.\n"
                + "They often do it in consultation with the writers. My original training was as a cellist. I later trained in linguistics. So if they have questions on classical musicians, linguists, they say, “Is this person important? Is this person worth doing?” I may weigh in. My colleagues weigh in similarly in their subject areas.\n"
                + "The criterion we look for, if we had to pick a single question that can be asked of every applicant at our gates, is: Did he or she change the culture?\n"
                + "    The criterion we look for, if we had to pick a single question that can be asked of every applicant at our gates, is: Did he or she change the culture?\n"
                + "COWEN: Who invented the lawn flamingo?\n"
                + "FOX: A very interesting man, a Massachusetts man with the wonderful and appropriate name of Don Featherstone. He trained as a sculptor. He got work in the postwar years at a plastics factory. It’s like that wonderful, famous old line from The Graduate — “I have one word of advice for you: plastics.” Well, he took that advice.\n"
                + "The plastics factory made all sorts of three-dimensional ornamental pieces for the home. He had the idea — and again, just in a stroke of inspiration — of making a creature that would connote the ongoing pleasure of endless summer. I think we say in the obit “the saturated pink promise of endless summer.” It took off in ways that he never imagined, sold millions and millions and millions, and literally changed the landscape of America.\n"
                + "COWEN: Now we have the saturated pink promise of endless summer because of him.\n"
                + "FOX: We do. I mean, perhaps had he not done it, someone else would have. But the point is, he did, and he was transformative enough — albeit in a perhaps campy way when viewed through a postmodern lens. The Times put him on page one.\n"
                + "COWEN: Take his obituary. Was a version of that written in advance because you were thinking, “My goodness, the lawn flamingo. That fellow has to pass on sooner or later. We’re going to be ready”? Or is there some other process through which you learned of his passing, maybe a local paper or a wire?\n"
                + "FOX: In his case, it was the latter. And I believe it was both a local paper and the wire.\n"
                + "It is indeed the case that obits for many of these major historical figures — presidents, Supreme Court justices, members of Congress, old-time silver screen stars — those are indeed written in advance.\n"
                + "The selection criterion is: Does this person have a life that — it was so long in the public eye, so rich, so complex, and so deeply documented that we wouldn’t want to get caught short writing his or her obit on deadline? Of course, very often we do because we’re a small department, and things happen.\n"
                + "COWEN: People die suddenly.\n"
                + "FOX: Right. Things happen. Rockers OD. Planes go down. Things happen. But in general, we try to have a certain level of preparedness with the major figures. We do indeed have the advance obits — all but the top, as it were — written, edited, on file. We have about 1,700.\n"
                + "That said, the vast majority of what my colleagues and I down in the trenches do, probably 90 percent of our working life, are daily obits that are found out about, reported, written, edited, copyedited, put in the paper all in the space of a single day, just like any other article in the paper.\n"
                + "COWEN: Of the thousand Times obituaries over the course of a year, how many of those have some early draft ready to go? Of course, it needs to be modified, but — .\n"
                + "FOX: There’s no way to predict. Sometimes we can literally have a day where three of our advances drop at once, and the editors get very busy trying to find either the original reporter or, if that person’s unavailable, someone else in the newsroom who can call the family, call the funeral home, get confirmation that, indeed, this person has died. Sometimes you can go for six months without having an advance drop.\n"
                + "Again, this is all in the hands of fate, and we are only men and women.\n"
                + "COWEN: But on average, below half, above half, half?\n"
                + "FOX: I’ve never kept track of it because it’s not quite in my wheelhouse. This is the editor’s headache. I have other headaches. But half of all the ones we have on file, half of all the ones we run — no, a very small percentage, I would say, of those we run in the print paper every year are advances. A number, I couldn’t tell you. I’m sorry.\n"
                + "COWEN: Now, this is not all true of your work or the Times today, but it used to be a long-standing joke that in the obituaries pages, women and black people never die because there was an emphasis on white males, say, 30, 40 years ago.\n"
                + "FOX: No. But remember, think about what an obit is. It is not only the most narrative genre in the paper; it is the most retrospective. We are writing about the movers and shakers who made our world. I think of obit writing as the act of looking through a sliding window onto the past, a kind of window that slides back along the rails of time.\n"
                + "When I first started the job in 2004, we were writing overwhelmingly about the people on either side of World War II. We edged up into the Cold War. We’re now writing about Vietnam and the civil rights era.\n"
                + "    I think of obit writing as the act of looking through a sliding window onto the past, a kind of window that slides back along the rails of time. When I first started the job in 2004, we were writing overwhelmingly about the people on either side of World War II. We edged up into the Cold War. We’re now writing about Vietnam and the civil rights era.\n"
                + "And no matter how we feel about it in light of modern sensibilities, the stark reality of our world is, pretty much the only people who were allowed to be actors on the world stage in the 1940s, ’50s, were overwhelmingly white men.\n"
                + "I’m happy to say that in the 12 years I’ve been doing this job, as that window has slid up into the civil rights era and even the women’s movement, that page of ours has started to diversify.\n"
                + "I had the great privilege, for instance, of writing our page-one obit of Betty Friedan, knowing full well that had it not been for her writing The Feminine Mystique in 1963 and launching the modern women’s movement, I would very likely not be in the newsroom of the New York Times writing a page-one story.\n"
                + "COWEN: Do you have a sense — which, by the way, I would completely favor — that somehow other people’s notions of history are not diverse enough but that with obituaries, by choosing a wiser selection or a deeper understanding of who is important, to bring a greater balance to our understanding of history by deliberately trying to introduce greater diversity to the selection of who gets covered?\n"
                + "FOX: Again, I’m the wrong person to ask. Our section editors make those calls. Because we can write about so few people, we are writing by definition about newsworthy people who either made news while they were alive or who quietly did something that made news.\n"
                + "Again — and I will repeat myself until I’m blue in the face — through no fault of anyone who is active in the world today, those people regrettably were overwhelmingly white men. We are not in the revision business. We can’t revise history, no matter how much it may be painful to look on it with hindsight.\n"
                + "COWEN: Are there obituaries of economists that stand out in your mind? Or maybe some you’ve written?\n"
                + "FOX: Well, interestingly, there is one. As I said, my original training was in classical music, so my editors almost jumped out of their skins with excitement when they discovered they could assign me the obituary of a Harvard economist named Richard T. Gill.\n"
                + "Now, why did they give that to me? Because as we say in the lede of the obit, “Richard T. Gill, in all statistical probability the only Harvard economist to sing 86 performances with the Metropolitan Opera, died,” etc., etc.\n"
                + "COWEN: Yes, I remember reading that one. That was before I knew that you were you.\n"
                + "FOX: I was me then. You just didn’t know it.\n"
                + "COWEN: Correct.\n"
                + "FOX: It’s, again, one of these wonderful, unexpected twists for all concerned, no one more so than for Richard T. Gill. He discovered when he was in his forties that he had this really good voice, started taking lessons, and amazingly was good enough to sing at the Met while teaching at Harvard.\n"
                + "Margalit Fox reads the kind of obituary that was “not possible a generation ago”\n"
                + "COWEN: Some newspapers don’t seem to run obituaries at all. I think one example would be the Wall Street Journal. What determines the level of interest in a newspaper in obituaries?\n"
                + "FOX: The Journal does. And again, I can’t speak to that because I’m not in newsroom administration; I’m not a publisher. But of course, you’re an economist. It’s economics.\n"
                + "I mean, sadly, even many major papers are scaling back or even eliminating their obit departments in this age of retrenchment, in the age of the incredible shrinking news hole, in the age where, heartbreakingly, newspaper are dying. I mean, I fear the last one to turn out the lights will be writing the obit of whatever is the last newspaper standing.\n"
                + "On finding a person’s story\n"
                + "COWEN: Do people whose obituaries are being written — those where the draft is written in advance — do they engage in much rent-seeking, trying to sway what the paper will do, how they will be covered? They ask to see a draft. Their publicists elbow people in the obituaries department. They try to manage their reputations. Or does this really not much go on?\n"
                + "FOX: Occasionally, although of course we would never let them. It is absolutely verboten for anyone to see a draft of his or her obit. The Times is not permitted to comment on or divulge the contents of any forthcoming news story. Of course, if you think about, an advance obit is kind of the ultimate forthcoming news story.\n"
                + "Famous people, for reasons of ego perhaps, can make an educated guess as to whether we have an obit of them on file, but they’re certainly never going to see it.\n"
                + "COWEN: But if they say, “Well, would you let me send you my bio?” do you just turn them away, or do you — .\n"
                + "FOX: No, because it may be useful to us for study purposes. We’re not going to tell them whether we’re going to use it or not.\n"
                + "And we do get — not for advance obits so much, but for daily obits on deadline where the subject has actually died — if a person has been in public life all of his or her life — and we usually see this for either politicians or particularly Hollywood people — and he or she has had a publicist in life, that publicist will occasionally send us this glossy press kit. I find it quite fascinating that there is this one last act of spin control attempted in death.\n"
                + "    …[I]f a person has been in public life all of his or her life — and we usually see this for either politicians or particularly Hollywood people — and he or she has had a publicist in life, that publicist will occasionally send us this glossy press kit. I find it quite fascinating that there is this one last act of spin control attempted in death.\n"
                + "COWEN: Every now and then, an especially tragic event happens. Obvious example I guess for New York would be 9/11. My sense is an especially high proportion of well-known people died on 9/11. When there’s a large number of deaths you might be covering all at once, how is that handled?\n"
                + "FOX: I was not involved with that in any way, nor was the obituary department directly. I would beg to differ with the contention that a large number of high-profile people died on 9/11. They became in a sense high-profile people because of the way they died, but very few of them were famous in conventional terms. That was one of the great heartbreaks. It was these ordinary working men and women, the people who had to be at work at a quarter to eight here in New York.\n"
                + "The Times of course did this marvelous, very moving series of little capsule obits on almost all of the 3,000 called “Portraits of Grief,” but that was not handled out of obits. A special team was convened in Metro to deal with that. And this was long before I was on the obit desk, in any case.\n"
                + "COWEN: Two individuals who are clearly obituary worthy, so to speak — one would be Thomas Pynchon, the other J. D. Salinger. Both disappeared from public view for decades on end. So, if one has to write the obituary of those individuals, what is it that one actually does? There are blank decades, or you know things already the rest of the world doesn’t know?\n"
                + "FOX: Well, again, I’ve not been involved with either, but I can make an educated guess as to what one would do. One would comb the clippings.\n"
                + "This would be an advance obit where the reporter would be given the comparative luxury of time, which means a week or even two weeks instead of four or five hours, to put something together — combs the clippings, of course makes every attempt to get to this elusive person, which is probably going to be impossible, but you have to try.\n"
                + "And then you interview around them. You interview their editors. You interview friends. You interview neighbors. You interview old lovers. You interview anyone and hope they haven’t been forbidden to talk or, if they have been, they don’t take it seriously. You assemble the best you can while, of course, explaining to readers, “This famously incommunicative person made sure that his life was obscure. Here’s what we know.” That’s all you can do.\n"
                + "COWEN: It’s an interesting question. People who knew them and maybe who were told not to talk — do you think there are any privacy issues with obituaries that we should worry about? So, in general, we believe in the public’s right to know, correct?\n"
                + "FOX: Absolutely.\n"
                + "COWEN: If there’s a political candidate, a historical event. But when people have passed away, obviously in some key ways they matter much less — and especially people who are not historical figures — but nonetheless, there’s an outline of a life. It may involve drug addiction or alcohol problems, illegitimate children, strange things that happened to them that maybe they want to keep secret.\n"
                + "Do you think, for a person who’s passed away, there are privacy rights of a sort that we should not tread on?\n"
                + "FOX: No, we’re not in the veneration business. We’re not eulogists. We will occasionally get families, particularly families who are not conversant in dealing with the press, who say, “Please put in, ‘He died surrounded by his loved ones.’ Please put in, ‘He touched the life of everyone he ever knew.’”\n"
                + "Apart from the fact that we would never use such hoary Victorian clichés, we know that’s the first thing to go on the cutting room floor. It has no place in a modern news obit.\n"
                + "A modern news obit is a news article like any other. The particular subtype it is — it’s a profile. Just as a profile of a living person you’d read in a newspaper or a magazine has to be balanced, so too do our portraits. Indeed, you sometimes get families who withhold information on Dad’s earlier marriages, other children.\n"
                + "And you’ll get children calling you up the day an obit runs, understandably in tears, saying, “How dare you write me out of my father’s story?” The only answer you can give is, “We were never told you existed.” We learn to ask all kinds of preemptive questions to try to forestall omissions like that.\n"
                + "COWEN: Part of your job must, in a sense, be as a therapist — that you’re handling grieving family members or non-family members, people who have agendas, maybe people jostling over the will or having that in mind. Some occasionally may even be happy, but more often than not, they’re tragically bereaved. All of these individuals you talk with, you have to manage, get them to cooperate. In a sense, you’re a psychologist of sorts.\n"
                + "FOX: My oldest childhood friend actually has two degrees, one in journalism and one in counseling. And she says the elicitation of information — that process is identical. Where they diverge, of course, is what you do with the information once you have it.\n"
                + "Indeed, we need to be very careful. We’re calling families at vulnerable times. They’re grieving; they’re exhausted; they’re sleep deprived; they have a million things to do. We need to be very careful that we not, however unwittingly, present ourselves as their friend, their advocate, their grief counselors.\n"
                + "That said, it behooves us — both journalistically, so they feel comfortable enough to talk to us and be candid, and in purely human terms — to treat them as well as possible within allowable, professional limits.\n"
                + "On Fox’s attitude towards death\n"
                + "COWEN: Doing all this, what do you think you have learned about the psychology of death that, say, maybe I wouldn’t know?\n"
                + "FOX: I don’t think there’s anything I’ve learned that any of us wouldn’t know. What I’ve learned is, death sucks. But I think I pretty much knew that before, and I think you pretty much know that, too.\n"
                + "    What I’ve learned is, death sucks. But I think I pretty much knew that before, and I think you pretty much know that, too.\n"
                + "COWEN: Worse than maybe you thought 15 years ago, before you were doing this?\n"
                + "FOX: Actually, no. The reverse, if anything. I’m very often asked, “Oh, you write obits. You’re around death every day. Isn’t that depressing?” I must admit, when I started the job full-time in 2004, I worried about that a little bit going in.\n"
                + "To my great joy and great relief, I found out right away, it’s almost never depressing. For all of these reasons we’ve discussed, in an obit of perhaps a thousand words, when you’re writing about someone fascinating who did something really interesting, often really wonderful, maybe a sentence or two will be about the death. The other 98 percent of the story is about the life.\n"
                + "In a strange way, with rare exceptions, writing obits is a kind of very life-affirming thing to do — and also wonderful because my colleagues and I are paid to tell stories. It doesn’t get much better than that.\n"
                + "COWEN: It’s often said, for instance, that the greatest works in the theater are tragedies — Hamlet, one, King Lear, two examples of many. Maybe we’re attracted to tragedy because in a sense it’s life-affirming, or it’s somehow cathartic. Writing about the deaths of individuals, you feel, gives you a better or maybe healthier perspective on life, in the same way that going to see a tragic work in the theater might.\n"
                + "FOX: Again, think of what was just said. It’s not tragedy. That’s my point. Writing about — it’s not the case that writing about obits is life-affirming because it’s tragedy. Writing about obits is life-affirming because it’s not tragedy.\n"
                + "COWEN: There’s a custom in some cultures, often eastern European, that if an individual has a terminal disease, they don’t tell the patient that. The person gets sicker but doesn’t know he or she is going to die. Do you have a view of this?\n"
                + "FOX: I have never encountered that one.\n"
                + "COWEN: But do you think it could possibly make sense? Could you imagine, say, that a person might prefer not to know he or she is going to pass away?\n"
                + "FOX: I would have to be a physician, a psychologist, a philosopher, or a cultural anthropologist to answer that. Again, that’s beyond my ken. I’m not going to take on something that’s beyond my ken. It would be horribly inappropriate.\n"
                + "COWEN: Is there any way in which you feel writing so much history — put aside the obituaries side of it, but just so much American and international history — has it changed how you think about your own life, what you should do with your time?\n"
                + "FOX: It does give one a carpe diem sense. Often when I lecture, particularly to young people, they who are so far from death are kind of obsessed with it. They always ask me, “What’s the weirdest cause of death you’ve ever had?” I say, “Well, one of my colleagues had a man who was eaten by a crocodile. And he was a naturalist going down a river; crocodile just leapt up and grabbed him.” It’s a pretty horrific way to go.\n"
                + "But for me it became kind of a metaphor. You never know, as you go through life, whether or not that crocodile is around the next bend in the river. So you might as well try to live as good a life as you can and enjoy the hell out of life before you get to that crocodile.\n"
                + "COWEN: Do you ever think of what you’re doing in any kind of theological terms? For instance, I went back — I looked at a very good book by your husband. It’s called Essential Judaism by George Robinson — that’s him?\n"
                + "It’s a wonderful book. There are two quotations from that book. I’ll read them. One is, “A dying person should not be left alone.” The other is, “Escorting the dead is one of the basic acts.” Not just those who are Jewish, but I think many people, would view this as an appropriate philosophy for thinking about death, dealing with death.\n"
                + "Do you ever think of what you’re doing as a kind of written version of carrying out some of this — escorting the dead in a literary way, and being with them, and having society process that in a matter which has a dimension which is not just news reporting but tied into views of the sacred and higher values? Or is that totally separate for you?\n"
                + "FOX: Again, I’m not a columnist, so I am paid to have no opinion. Which means — .\n"
                + "COWEN: Your personal opinion.\n"
                + "FOX: Which means I’m paid to have no discernible politics and also no discernible religion. Whether or not I am a religious believer in my private life is not germane. But metaphorically, indeed, there is an aspect of writing obits where one feels one is charged with the rather weighty responsibility of ushering people out.\n"
                + "Now, these are not always people to whom flights of angels will sing to rest. We are obliged to write news obits not only of the great heroes of history but also the great villains. I wrote the obit of Jim Clark, Sheriff Jim Clark, the great enforcer of segregation in Jim Crow Alabama. It was his billy club that was coming down on demonstrators’ heads as they tried to cross the Edmund Pettus Bridge.\n"
                + "I’ve written obits of Nazi war criminals. So we run the whole gamut. Again, the salient question is, “Did this person make history?” — for good but also for ill. And so, we have to usher those people out, too, and in those cases you don’t have a warm, fuzzy feeling. You feel like you want to go home, take a shower, and have a good, stiff drink afterward. But it’s part of the job. It has to be done right.\n"
                + "    I wrote the obit of Jim Clark, Sheriff Jim Clark, the great enforcer of segregation in Jim Crow Alabama. It was his billy club that was coming down on demonstrators’ heads as they tried to cross the Edmund Pettus Bridge. I’ve written obits of Nazi war criminals. So we run the whole gamut. Again, the salient question is, “Did this person make history?” — for good but also for ill. And so, we have to usher those people out, too, and in those cases you don’t have a warm, fuzzy feeling. You feel like you want to go home, take a shower, and have a good, stiff drink afterward.\n"
                + "On things under- and overrated\n"
                + "COWEN: Now, there’s a segment of all of these conversations. It’s called underrated/overrated. I mention a name or a thing; I ask you if you think it’s underrated or overrated. You’re free to pass on any of these, but I’ll try just a few.\n"
                + "The pet rock. Overrated or underrated?\n"
                + "FOX: Well, I’m coming from a position of extreme bias — .\n"
                + "COWEN: That’s fine.\n"
                + "FOX: Because I, again, did the obit of the inventor of the pet rock, a man named Gary Dahl. And it was neither overrated nor underrated. It was a beautiful example of what it was. It was a totemic thing that caught the fancy of this kind of cheesy seventies pop culture. With hindsight, overrated perhaps. Had it not been overrated, we wouldn’t have gotten a story out of it.\n"
                + "COWEN: Now, you have a background as a cellist, I understand. Pablo Casals. Overrated or underrated?\n"
                + "FOX: Wonderfully rated. I mean, I think he can never be rated highly enough, but it was he — and this is well documented through his series of televised master classes around the world in the very early sixties — who really caused the instrument’s popularity to soar. Most people had really not conceived of the cello as a solo instrument before; it was just sort of going oompah-pah at the bottom of the orchestra.\n"
                + "He was rated magnificently, but by the same token, you can never rate him too highly because he was wonderful.\n"
                + "COWEN: What if I say, “Well, Casals was a bit like Schnabel. He had incredible profundity, but there’s just too much scraping on a lot of his recordings, and in some ways they’re hard to listen to today”? He was path-breaking, but if you were to sit down and put on, say, the Bach cello suites, actually very few people, including cello lovers, would pick Casals, right?\n"
                + "They’d pick János Starker, they’d pick Heinrich Schiff, or — do you agree or not?\n"
                + "FOX: It’s true, in light of modern sensibilities, you can certainly hear squeaks and occasional bits of strangeness in Casals’s cello suites. I suspect he was older when he recorded them. He lived to be, of course, almost 100. Recording technology has improved since then, and I think he was on such an exalted plane that he gets a bye. He can be and should be forgiven any of these little transgressions that make him seem mortal.\n"
                + "COWEN: If you had to pick a favorite cellist — I know it’s hard to do, but do you have a pick?\n"
                + "FOX: It depends on the genre. I like different cellists for different things. The great, doomed Jacqueline du Pré, of course, was a wonderful cellist. Rostropovich. Starker, whose obit I wrote.\n"
                + "COWEN: You have a wonderful book called The Riddle of the Labyrinth: The Quest to Crack an Ancient Code, where you study the world before ancient Greece. Fantastic book. It’s a story of how, after cracking the code, we learned a lot of it was actually about accounting, economic themes.\n"
                + "But I’ll ask you. Homer’s Odyssey. Overrated or underrated?\n"
                + "FOX: Again, can’t rate it highly enough.\n"
                + "COWEN: Can’t rate it highly enough. We agree. Adverbs. Overrated or underrated?\n"
                + "FOX: Overused.\n"
                + "COWEN: Overused, so they’re overrated, in a sense. Maurice Sendak, the author of famous children’s stories — Where the Wild Things Are — maybe the wild things are the children, right? Overrated or underrated?\n"
                + "FOX: Again, can’t rate him highly enough. And his legacy will endure. Again, his obit, I had the privilege of doing. The Times put it on page one. When is the Times ever going to put a picture-book author on page one? That’s how magnificent he was and how newsworthy.\n"
                + "COWEN: Was there something surprising you learned about him doing his obit?\n"
                + "FOX: I think just what a melancholic he was. Now, that’s far from unusual for creative people, but it was — his personal story was rather painful. He was someone who grew up poor, Jewish, knowing he was gay in this very repressive era. He was a deeply, deeply melancholy man. Of course, it comes through in the work, as well.\n"
                + "COWEN: Studying all these different lives, from so many walks of life, different countries, to some extent different eras, what in life do you feel is underrated or overrated, say, by your readers?\n"
                + "Various clichés like, “Oh, I spend too much time in the office, not enough with family” — so many people say that. I don’t actually believe they necessarily really mean it. But what do you feel on that after studying all this history? What in life is underrated?\n"
                + "FOX: Well, I think list questions are overrated, if you’ll forgive me. What in life is underrated? Silence. Stillness. Reading real books on paper.\n"
                + "COWEN: Those are all underrated.\n"
                + "FOX: Having real human contact rather than the social media that’s become, in our atomized, postmodern lives, a substitute for real contact.\n"
                + "COWEN: How important do you think Dear Abby was for American life?\n"
                + "FOX: Dear Abby and her twin sister Ann Landers, both of whose obits I had the privilege of doing, were fascinatingly important and remain so, retrospectively, as barometers of the way the country was going to go.\n"
                + "They were both these very pragmatic women who, while not being firebrands in any sense, were just a little bit left of center because they embodied a kind of progressive mid-century humanism. And so, they were a very, very interesting index of the direction in which progressives were trying to nudge the country in those years.\n"
                + "On the pleasures of puzzle-solving\n"
                + "COWEN: You have another book — it’s called Talking Hands. It’s about the sign language which developed in a Bedouin village in Israel, correct?\n"
                + "FOX: That’s right.\n"
                + "COWEN: Is that a fair way to describe it?\n"
                + "FOX: Absolutely.\n"
                + "COWEN: You have these two books. There’s also an e-book of your obituaries, which you can buy for your Kindle. And then there are the obituaries you write. Do you see any underlying unity to your writings, including your next novel on — it’s a kind of Edwardian crime story. What ties it all together?\n"
                + "FOX: It’s a nonfiction book. My next book, which is my third after these two, is narrative nonfiction. I’m capable only, it seems, of writing nonfiction. I was born without the fiction-writing gene, alas. What underpins the two of my books that are out, the third book that’s coming, my work at the Times, is narrative. I care passionately about narrative.\n"
                + "I care passionately about storytelling and the privilege of telling stories, albeit in the nonfiction genre.\n"
                + "COWEN: Somehow the idea of cracking a code or unraveling a mystery, to me, seems to run throughout all your work. There’s a kind of mystery of a life, which you’re never going to state but maybe very subtly hint at, especially with those first and last sentences. Talking Hands is about figuring out a sign language and how it came to be. Riddle of the Labyrinth is very explicitly about cracking a code.\n"
                + "So, is that a common theme in your thought? Or solving this Edwardian mystery — I haven’t read that book yet, but — .\n"
                + "FOX: Yes, I think that’s right. I’m passionately interested in heuristics. When I was a kid, my friends and I — you know, back when kids engaged in real play and didn’t just sit with their palm devices — we used to make little treasure hunts for each other. It’s all about heuristically following clues from A to B to C to get — the goal is not the thing itself. The treasure was just some silly little prize or nothing at all.\n"
                + "It was just the chance to work through all the clues and see if you were on the right lines. Here, too, unpacking a sign language that’s never been analyzed. In Riddle of the Labyrinth, unraveling this Aegean script that was unearthed on clay tablets in 1900, not solved for 50 years because they not only didn’t know what the tablets said when they were unearthed on Crete, they didn’t know what language they were in. It’s a black box. How do you penetrate that?\n"
                + "In obits, too, what are the heuristics of a life that allows someone to get from A to B to C to D, all the way to Z when I get them, in his or her life? How much of that is free will, and how much of that is determined by pure, blind fate?\n"
                + "COWEN: I get that you may not have that much spare time, given all that you do. But if you’re going to read something for fun in your spare time, what’s that likely to be, research aside?\n"
                + "FOX: Narrative nonfiction. The great contemporary masters — John McPhee, Tracy Kidder — plus the wonderful old masters of essays — E. B. White, Red Smith, Twain of course. Always Twain.\n"
                + "Twain is completely symptomatic for the people I love to read because you not only get the paramount stylist, the nonpareil of stylists, but you can also see through the writing. It’s a window onto how the man’s mind works. And that, I love.\n"
                + "On advice for young writers\n"
                + "COWEN: Final question. I know this is a tough one. Someone comes up to you and says, “I so much admire your work. I would love to write obituaries for a living.” I know there are not many paths into this, but what advice would you give them?\n"
                + "FOX: I would say, don’t feel you can or should specialize. The child has not been born who comes home from first grade clutching a theme that says, “When I grow up, I want to be an obituary writer.” Be a journalist first. Go to journalism school.\n"
                + "That’s what I did. When I was 30, I chucked my unfulfilling jobs in book and magazine publishing and went to Columbia journalism school, got a master’s, and have been in newspapers ever since.\n"
                + "Go to journalism school. Be a journalist. Writing obits — and here we’ve come nicely full circle — writing obits is just one way of doing journalism, a very satisfying narrative way.\n"
                + "COWEN: Thank you very much, and we all look forward to your next book coming out next summer.\n"
                + "FOX: Thank you.";
        int n = 1;
        HashMap<WordList, Ocurrences> l = new HashMap();
        char[] words = s.toCharArray();
        for (int i = 0; i < words.length - n; ++i) {
            char[] s2 = new char[n];
            for (int j = 0; j < n; ++j) {
                s2[j] = words[i + j];
            }
            WordList o = new WordList(s2);
            l.putIfAbsent(o, new Ocurrences());
            l.get(o).occur(words[i + n]);
        }
        int n2 = (int) (Math.random() * 100);
        char[] result = new char[n2];
        int k = 0;
        for (char c : l.keySet().iterator().next().words) {
            result[k] = c;
        }
        k++;
        Ocurrences current = l.entrySet().iterator().next().getValue();
        for (int i = n; i < n2 - n; ++i) {
            result[i] = current.generate();
            current = l.get(new WordList(Arrays.copyOfRange(result, i - n + 1, i + 1)));
        }
        for (char st : result) {
            System.out.print(st);
        }

    }*/

}
